gate_manager:
  ros__parameters:
    freq: 150.0

# ------------------ #

pot_parser:
  ros__parameters:
    id: 1
    length: 2
    scale: 100

# ------------------ #

imu_parser:
  ros__parameters:
    id: [ 4, 3, 7]                # rpy, vel, acc IDs
    available: [true, false, true]# expect RPY & ACC only; VEL ignored
    cov: [0.01, 0.1, 5.0]
    link: imu_link
    tf: [ 0.0, 0.0, 0.0, 180.0, 0.0, 0.0]   # x,y,z, roll,pitch,yaw (radians)
    tf_publish_hz: 10.0
    publish_pose: true
    publish_ypr:  true

