version: '3'

services:
  jazzy:
    build: ./
    image: orca:jazzy-desktop
    container_name: orca-computer
    user: ros
    environment:
      - DISPLAY=host.docker.internal:0
      - QT_X11_NO_MITSHM=1  # Avoids potential issues with shared memory
    volumes:
      -  _path_to_repo_/ros2_ws:/home/ros/ros2_ws
      - /tmp/.X11-unix:/tmp/.X11-unix  # Mounts the X11 socket
    network_mode: host  # Uses the host network
    ipc: host
    privileged: true
    # Open in the background as bash
    tty: true
    command: bash 
