pot_parser:
  ros__parameters:
    id: 1
    length: 2
    scale: 100
    use_sim_time: true

# ------------------ #

imu_parser:
  ros__parameters:
    id: [ 4, 3, 7]                # rpy, vel, acc IDs
    available: [true, false, true]# expect RPY & ACC only; VEL ignored
    cov: [0.01, 0.1, 5.0]
    link: imu_link
    tf: [ 0.0, 0.0, 0.0, 180.0, 0.0, 0.0]   # x,y,z, roll,pitch,yaw (radians)
    tf_publish_hz: 10.0
    publish_pose: true
    publish_ypr:  true
    use_sim_time: true

ekf_node:
    ros__parameters:

        frequency: 30.0
        sensor_timeout: 0.1
        two_d_mode: true
        transform_time_offset: 0.0
        transform_timeout: 0.0
        print_diagnostics: true
        debug: false
        debug_out_file: /tmp/ekf_debug.txt
        permit_corrected_publication: false
        publish_acceleration: false
        publish_tf: true
        map_frame: map              # Defaults to "map" if unspecified
        odom_frame: odom            # Defaults to "odom" if unspecified
        base_link_frame: base_link  # Defaults to "base_link" if unspecified
        world_frame: map    # Defaults to the value of odom_frame if unspecified

        odom0: /myodometry/gps
        odom0_config: [true,  true,  false,
                       false, false, false,
                       false, false, false,
                       false, false, false,
                       false, false, false]
        odom0_queue_size: 10
        odom0_differential: false
        odom0_relative: true
        odom0_pose_use_child_frame: false

        imu0: /imu_data
        imu0_config: [false, false, false,
                      true,  true,  true,
                      false, false, false,
                      true,  true,  true,
                      true,  true,  true]
        imu0_differential: false
        imu0_relative: false
        imu0_queue_size: 10
        imu0_pose_rejection_threshold: 0.8                 # Note the difference in parameter names
        imu0_twist_rejection_threshold: 0.8                #
        imu0_linear_acceleration_rejection_threshold: 0.8
        imu0_remove_gravitational_acceleration: false

        use_control: false
        use_sim_time: true